export * from './LandingPage';
export * from './HomePage';
export * from './LoginPage';
export * from './RegisterPage';
export * from './RecordingListPage';
export * from './CapturePage';
export * from './TesPage';
export * from './ResultPage';
export * from './ProgressPage';
